In [1]:
import numpy as np
import pandas as pd       

### Генерация случайной матрицы

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,100).

Функция для генерации чисел из нормального распределения: np.random.normal

Параметры:

loc: среднее нормального распределения (в нашем случае 1)
scale: стандартное отклонение нормального распределения (в нашем случае 10)
size: размер матрицы (в нашем случае (1000, 50))

In [2]:
data = np.random.normal(loc=1, scale=10, size=(1000, 50))
print(data)

[[ -0.78904023  -2.02103514   3.29179092 ...  -6.3470514   -3.09784688
    8.9224773 ]
 [ 19.74193166 -16.37432682 -21.16143132 ...  -9.50297157   4.25563868
   -6.14429137]
 [  3.95721023   0.71029001  -3.85270215 ...  17.11987502 -13.44324448
   22.19901571]
 ...
 [-28.89306232   4.35464212   2.58475886 ...   3.23140384 -18.5688462
  -13.1652091 ]
 [  3.10405437   5.07979926 -10.34672901 ...  10.6046241   12.64188854
   -7.24108988]
 [  9.45764209   2.04198954   8.98858456 ...  -9.09599911  20.19926591
   -8.67828769]]


### Нормировка матрицы

Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

Функция для вычисления среднего: np.mean

Функция для вычисления стандартного отклонения: np.std

Первый параметр — матрица, для которой производятся вычисления. Также полезным будет параметр axis, который указывает, по какому измерению вычисляются среднее и стандартное отклонение (если axis=0, то по столбцам, если axis=1, то по строкам; если его не указывать, то данные величины будут вычислены по всей матрице).

In [3]:
meanVal = np.mean(data, axis=0)
stdVal = np.std(data, axis=0)
dataNorm = (data - meanVal) / stdVal
print(dataNorm)

[[-0.1583626  -0.3094911   0.18516453 ... -0.72859087 -0.36211852
   0.76256058]
 [ 1.91778866 -1.75841043 -2.24493769 ... -1.05518899  0.37553526
  -0.68775375]
 [ 0.32159198 -0.03377248 -0.52483795 ...  1.69994142 -1.39990144
   2.04054887]
 ...
 [-3.0003226   0.33411332  0.11490139 ...  0.262659   -1.91406842
  -1.36358131]
 [ 0.23531839  0.40731564 -1.17019867 ...  1.02569474  1.21678923
  -0.79333064]
 [ 0.87781155  0.10065837  0.75129813 ... -1.01307245  1.97489611
  -0.93167407]]


### Операции над элементами матрицы

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

Функция для подсчета суммы: np.sum

Аргументы аналогичны функциям np.mean и np.std.

К матрицам можно применять логические операции, которые будут применяться поэлементно. Соответственно, результатом такой операции будет матрица такого же размера, в ячейках которой будет записано либо True, либо False. Индексы элементов со значением True можно получить с помощью функции np.nonzero.

In [4]:
data = np.array([[4, 5, 0], 
                 [1, 9, 3],              
                 [5, 1, 1],
                 [3, 3, 3], 
                 [9, 9, 9], 
                 [4, 7, 1]])
rowSum = np.sum(data, axis=1)
rowSumGreater10 = rowSum > 10
print(np.nonzero(rowSumGreater10))

(array([1, 4, 5]),)


### Объединение матриц

Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

Функция для генерации единичной матрицы: np.eye

Аргумент: число строк (или, что эквивалентно, столбцов).

Функция для вертикальной стыковки матриц: np.vstack((A, B))

In [5]:
data = np.eye(3)
mergedData = np.vstack((data, data))
print(mergedData)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
